# Generated by Django 3.2.16 on 2022-10-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_healthcare_profesional',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_hospital',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_insurance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_pharmacy',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('insurance', 'Insurance Company'), ('professional', 'Healthcare Professional')], default='patient', max_length=30),
            preserve_default=False,
        ),
    ]
