# Generated by Django 3.2.16 on 2022-10-26 14:53

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
