# Generated by Django 4.1.2 on 2022-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_products_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
