# Generated by Django 3.2.16 on 2022-11-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userfiles_user'),
        ('accounts', '0013_insuranceclaim'),
    ]

    operations = [
    ]
