# Generated by Django 3.2.16 on 2022-11-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_0013_alter_userfiles_user_0013_insuranceclaim'),
        ('accounts', '0014_sharedfiles'),
    ]

    operations = [
    ]
