# Generated by Django 3.0.5 on 2022-11-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20221125_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
