# Generated by Django 3.0.5 on 2022-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20221125_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsshared',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
