# Generated by Django 3.2.16 on 2022-11-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_amount_amountshared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='symp',
            new_name='amount',
        ),
    ]
