# Generated by Django 3.2.16 on 2022-11-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_insurance_insuranceshared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='amount',
            new_name='ins_amount',
        ),
        migrations.RenameField(
            model_name='insuranceshared',
            old_name='amount',
            new_name='ins_amount',
        ),
    ]
