# Generated by Django 3.2.16 on 2022-11-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20221127_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='symm_key',
            field=models.CharField(default=1234567890, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
