# Generated by Django 3.2.16 on 2022-11-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20221128_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
