# Generated by Django 3.2.16 on 2022-11-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_pharmacyrequest_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountshared',
            name='prescription',
        ),
        migrations.AddField(
            model_name='pharmacyrequest',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.amountshared'),
        ),
    ]
