# Generated by Django 3.2.16 on 2022-11-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_pharmacyrequest_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountshared',
            name='completed',
        ),
    ]
