# Generated by Django 3.2.16 on 2022-11-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_amountshared_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrequest',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='accounts.sharedfiles'),
        ),
        migrations.AlterField(
            model_name='pharmacyrequest',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='accounts.sharedfiles'),
        ),
    ]
